### ISSUE TITLE
about the datasets

### ISSUE THREAD

**Issue by darkdepth** [nexusapoorvacus/DeepVariationStructuredRL#1]
Hi!I am very grateful to you for implementing this article, because I searched for many times and did not find the specific implementation of the code. But I still want to ask you where I can find the training set you used, the training set I went with the paper tip to find, and so many kinds that I do not know which one can be used in your code. Thank you very much for your reply. If you feel that I am offensive in language, please forgive me, because English is not my native language. I am not very clear translation is polite. wish you a happy life.

**Comment by nexusapoorvacus** [comment]
Hi! The dataset used in the paper as well as the one I am using is Visual Genome. It can be found here: http://visualgenome.org/. You can find objects, relationships, scene graphs, and more in this dataset.

**Comment by darkdepth** [comment]
Thank you very much for your reply, but please forgive my stupid, I still do not quite understand train_data.json which one.

**Comment by nexusapoorvacus** [comment]
The file create_data_samples.py will generate this file. Since this repo is still a work in progress, I have not included instructions on how to set up, train, and evaluate this model. However in the next two weeks it will be complete. Please stay tuned for more updates to files/instructions in the next couple of days.

**Comment by darkdepth** [comment]
Thank you for informing, I very much look forward to your follow-up work. Thank you again for your patience and wish you a happy life : )
